languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Haojin's Blog"
description = "CompSci + PoliSci undergrad at Duke University: Coding thoughts into reality."
copyright = "@2018-2023 Haojin Li"

dateFormat = "January 2, 2006"

[params]
  mainSections = ["posts"]

[author]
  name = "Haojin Li"
  image = "img/avatar.png"
  bio = "CompSci + PoliSci undergrad - because one major alone wasn't enough to confuse me."
  links = [
    { home = "https://haojin.li"},
    { email = "mailto:hi@haojin.li" },
    { github = "https://github.com/declan-haojin" },
    { linkedin = "https://linkedin.com/in/haojinli" },
    { rss = "/index.xml"}
  ]
