# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 20

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 30

# [[main]]
#   name = "Projects"
#   pageRef = "projects"
#   weight = 35

[[main]]
  name = "Friends"
  pageRef = "friends"
  weight = 40

[[main]]
  name = "Places"
  pageRef = "map"
  weight = 45

[[main]]
  name = "About"
  pageRef = "about"
  weight = 50

[[main]]
  name = "Travelling"
  url = "https://www.travellings.cn/go.html"
  weight = 60
  [main.params]
    icon = "train"
    showName = false
    target = "_blank"


[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "Subscribe"
  url = "https://follow.it/haojin-s-blog?leanpub"
  weight = 10
  [footer.params]
    target = "_blank"

[[footer]]
  name = "Archives"
  pageRef = "archives"
  weight = 20
