version: 4.0.0
variant: default
logo: /media/logo.png
head:
    favicon: /media/favicon.png
    # Web application manifests configuration
    # https://developer.mozilla.org/en-US/docs/Web/Manifest
    manifest:
        # Name of the web application (default to the site title)
        name:
        # The displayed name of the web application
        # when there is not enough space to display full name
        short_name:
        # The start URL of the web application
        start_url:
        # The default theme color for the application
        theme_color: #0FFF95
        # A placeholder background color for the application page to display
        # before its stylesheet is loaded
        background_color:
        # The preferred display mode for the website
        display: standalone
        # Image files that can serve as application icons for different contexts
        icons:
            -
                # The path to the image file
                src: ''
                # A string containing space-separated image dimensions
                sizes: ''
                # A hint as to the media type of the image
                type:
    # Open Graph metadata
    # https://hexo.io/docs/helpers.html#open-graph
    open_graph:
        # Page title (og:title) (optional)
        # You should leave this blank for most of the time
        title:
        # Page type (og:type) (optional)
        # You should leave this blank for most of the time
        type: blog
        # Page URL (og:url) (optional)
        # You should leave this blank for most of the time
        url:
        # Page cover (og:image) (optional)
        # You should leave this blank for most of the time
        image:
        # Site name (og:site_name) (optional)
        # You should leave this blank for most of the time
        site_name:
        # Page author (article:author) (optional)
        # You should leave this blank for most of the time
        author:
        # Page description (og:description) (optional)
        # You should leave this blank for most of the time
        description:
        # Twitter card type (twitter:card)
        twitter_card:
        # Twitter ID (twitter:creator)
        twitter_id:
        # Twitter Site (twitter:site)
        twitter_site:
        # Google+ profile link (deprecated)
        google_plus:
        # Facebook admin ID
        fb_admins:
        # Facebook App ID
        fb_app_id:
    # Structured data of the page
    # https://developers.google.com/search/docs/guides/intro-structured-data
    structured_data:
        # Page title (optional)
        # You should leave this blank for most of the time
        title:
        # Page description (optional)
        # You should leave this blank for most of the time
        description:
        # Page URL (optional)
        # You should leave this blank for most of the time
        url:
        # Page author (article:author) (optional)
        # You should leave this blank for most of the time
        author:
        # Page publisher (optional)
        # You should leave this blank for most of the time
        publisher:
        # Page publisher logo (optional)
        # You should leave this blank for most of the time
        publisher_logo:
        # Page images (optional)
        # You should leave this blank for most of the time
        image:
    # Additional HTML meta tags in an array
    meta:
        # Meta tag specified in <attribute>=<value> style
        # E.g., name=theme-color;content=#123456 => <meta name="theme-color" content="#123456">
        - ''
    # URL or path to the website's RSS atom.xml
    rss:
navbar:
    menu:
        Home: /
        Archives: /archives
        Categories: /categories
        Tags: /tags
        About: /about
    links:
        Home:
            icon: fas fa-home
            url: https://haojin.li
        Travelling:
            icon: fas fa-subway
            url: https://www.travellings.cn/go.html
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/ppoffice/hexo-theme-icarus
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: false
    update_time: false
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
search:
    type: insight
comment:
    type: valine
    app_id: HuNpXmIPKbg14IMlvR0SXVi2-gzGzoHsz
    app_key: hVt2zoca8kRBW7QyNDnEUuh6
    notify: true
    verify: true
    placeholder: Feel free to leave your email address if you want to receive a notification once replied :)
sidebar:
    left:
        sticky: true
    right:
        sticky: false
widgets:
    -
        position: left
        type: toc
        index: false
        collapsed: true
        depth: 3
    -
        position: left
        type: profile
        author: Haojin Li
        author_title: Keep Mindful Living.
        location: Durham, NC
        avatar: /media/avatar.png
        avatar_rounded: true
        gravatar:
        follow_link: https://follow.it/haojin-s-blog?action=followPub
        social_links:
            Home:
                icon: fas fa-home
                url: https://haojin.li
            Github:
                icon: fab fa-github
                url: https://github.com/declan-haojin
            LinkedIn:
                icon: fab fa-linkedin-in
                url: https://www.linkedin.com/in/haojinli/
            Email:
                icon: fas fa-envelope
                url: mailto:hi@haojin.li
    -
        position: left
        type: links
        links:
            Duke APO: https://sites.duke.edu/dukeapo/
            Duke Code+: https://codeplus.duke.edu/projects/duke-fixit-issue-reporting-app-duke
    -
        position: right
        type: recent_posts
    -
        position: right
        type: categories
        depth: 2
    -
        position: right
        type: archives
    -
        position: right
        type: tags
    -
        position: left
        type: followit
        description:
        action_url: https://api.follow.it/subscription-form/WThEUWJudnVma1k3bWVUNXBLeXJpckJhTGZ3RWlOYVRDUXIvQUV6dExxMEhHQk5WYzMxdHcyajVYeGpJVStndkNITDlPSmNNakJaWTkwS1VDcUNtd3A2aXR4cE04QjBhL1EwVHlaNlpKZENkcDNYZXhncXZDK3lldnFwdVIzNUx8YjJwU1cySC83SDlwRzJBVmUxamk4ZXhUYWJ3M0pQRldTQkhTcHNhQ3QrTT0=/8
        verification_code: 11q4c1H6bRelaFP8Xu25
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id:
    bing_webmaster:
        tracking_id:
    busuanzi: false
    cnzz:
        id:
        web_id:
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id: G-EPZN5D7Z86
    hotjar:
        site_id:
    katex: false
    mathjax: false
    outdated_browser: false
    progressbar: true
    statcounter:
        project:
        security:
    twitter_conversion_tracking:
        pixel_id:
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
